### ISSUE TITLE
设置--token authentication后无法SSL解密

### ISSUE THREAD

**Issue by ludacriz** [nondanee/UnblockNeteaseMusic#142]
在这里需要加入if(!ctx.req.socket.encrypted && ...

https://github.com/nondanee/UnblockNeteaseMusic/blob/a7980e486a7cc06df89b61efc2eadeede15ead33/server.js#L62

不然https surrogate也要求验证了
或者重定向https的时候加上credential

**Comment by nondanee** [comment]
没懂，能不能举个例子？

**Comment by ludacriz** [comment]
repro:

```
  test:
    image: nondanee/unblockneteasemusic
    environment:
      NODE_ENV: production
    volumes:
      - ./certs/server.key:/usr/src/app/server.key
      - ./certs/server.crt:/usr/src/app/server.crt
    command: -p 8080:8081 -t user:password
    ports:
      - "127.0.0.1:8080:8080"
```


`curl -x http://user:password@localhost:8080 https://music.163.com`
返回空

因为流量从http server -> https server -> music.163.com，https和http用的同一个request handler，所以流量转发到https的时候还要求authenticate一遍，但其实没有必要
