### ISSUE TITLE
mac设置失败求助

### ISSUE THREAD

**Issue by ahmczsy** [nondanee/UnblockNeteaseMusic#389]
系统：mac14
网易云版本：832
启动方式：阿里云服务器上docker启动
代理使用：clashx
证书：使用的是docker内自带的证书

* docker compose配置
```yaml
version: "3"
services:
  netease:
    image: nondanee/unblockneteasemusic:latest
    restart: always
    hostname: host_netease_proxy
    container_name: netease_proxy
    ports: 
      - 443:8081
      - 1633:8080
    command: -p 8080:8081
```
* clash配置文件
```yaml
Proxy:
- { name: "UnblockNeteaseMusic", type: http, server: "保密", port: 443}
Proxy Group:

Rule:
- DOMAIN-SUFFIX,163.com,UnblockNeteaseMusic
- DOMAIN-SUFFIX,music.163.com,UnblockNeteaseMusic
- DOMAIN-SUFFIX,netease.com,UnblockNeteaseMusic
- GEOIP,CN,DIRECT
- MATCH,DIRECT
```

我启动网易云时到clash log有如下错误
<img width="484" alt="图片" src="https://user-images.githubusercontent.com/37166916/74583639-ed9f8580-5003-11ea-843f-eb0fc5797d95.png">
