### ISSUE TITLE
docker-compose 懒人搭建指南

### ISSUE THREAD

**Issue by levinneed** [nondanee/UnblockNeteaseMusic#401]
测试环境：macOS Docker 2.2.0.3

（Docker容器只暴露55555这一个端口，连接方式为Shadowsocks，更安全）

一、签发证书并信任CA：

进阶配置 #48：[https://github.com/nondanee/UnblockNeteaseMusic/issues/48](https://github.com/nondanee/UnblockNeteaseMusic/issues/48)

二、新建路径：Finder前往-前往文件夹（⇧⌘G：~/），依次新建Docker、unblock、cert、v2ray文件夹

```
~/Docker/unblock/docker-compose.yml

~/Docker/unblock/v2ray/config.json

~/Docker/unblock/cert/server.key

~/Docker/unblock/cert/server.crt
```

* *请自行修改端口 55555，密码 PPPPPPPPPPP，服务器地址127.0.0.1*

docker-compose.yml 内容：

```
version: "3"

services:

  unblockmusic:
    container_name: unblockmusic
    restart: always
    image: nondanee/unblockneteasemusic:latest
    environment:
      NODE_ENV: production
    expose:
      - 8080
      - 8081
    volumes:
      - ~/Docker/unblock/cert/server.key:/usr/src/app/server.key
      - ~/Docker/unblock/cert/server.crt:/usr/src/app/server.crt
    command: -p 8080:8081 -s -e https://music.163.com

  unblockv2ray:
    container_name: unblockv2ray
    restart: always
    image: v2fly/v2fly-core:latest
    ports:
      - "55555:55555"
    volumes:
      - ~/Docker/unblock/v2ray/config.json:/etc/v2ray/config.json
    depends_on:
      - unblockmusic
```

config.json 内容：

```
{
  "log": {
    "loglevel": "warning"
  },

  "inbounds": [
    {
      "port": 55555,
      "protocol": "shadowsocks",
      "settings": {
        "method": "chacha20-ietf-poly1305",
        "ota": false,
        "password": "PPPPPPPPPPP"
      }
    }
  ],

  "outbounds": [
    {
      "protocol": "http",
      "settings": {
        "servers": [
          {
            "address": "unblockmusic",
            "port": 8080
          }
        ]
      }
    }
  ]
}
```
三、启动Docker：

```
$ cd ~/Docker/unblock
$ docker-compose up -d
```

完工，以下为参考配置：

Shadowsocks连接信息：

```
类型：shadowsocks
端口：55555
加密方式：chacha20-ietf-poly1305
密码：PPPPPPPPPPP
```

Surge 配置：

```
[Proxy]
🔰 Direct = direct
⛺️ V2ray = ss, 127.0.0.1, 55555, encrypt-method=chacha20-ietf-poly1305, password=PPPPPPPPPPP, udp-relay=false, tfo=false

[Proxy Group]
🔊 Netease = select, 🔰 Direct, ⛺️ V2ray

[Rule]
PROCESS-NAME,com.docker.vpnkit,🔰 Direct
PROCESS-NAME,NeteaseMusic,🔊 Netease
USER-AGENT,NeteaseMusic*,🔊 Netease
USER-AGENT,%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90*,🔊 Netease

DOMAIN-SUFFIX,music.163.com,🔊 Netease
DOMAIN-SUFFIX,music.126.net,🔊 Netease
DOMAIN-SUFFIX,api.iplay.163.com,🔊 Netease

# IP-CIDR,59.111.181.60/32,🔊 Netease
# IP-CIDR,223.252.199.66/32,🔊 Netease
# IP-CIDR,223.252.199.67/32,🔊 Netease
# IP-CIDR,59.111.160.195/32,🔊 Netease
# IP-CIDR,59.111.160.197/32,🔊 Netease
# IP-CIDR,59.111.181.35/32,🔊 Netease
# IP-CIDR,59.111.181.38/32,🔊 Netease
# IP-CIDR,39.105.63.80/32,🔊 Netease
# IP-CIDR,47.100.127.239/32,🔊 Netease
# IP-CIDR,118.24.63.156/32,🔊 Netease
# IP-CIDR,193.112.159.225/32,🔊 Netease
# IP-CIDR,59.111.181.155/32,🔊 Netease
# IP-CIDR,115.236.118.33/32,🔊 Netease
# IP-CIDR,59.111.128.0/17,🔊 Netease
# IP-CIDR,115.236.112.0/20,🔊 Netease
# IP-CIDR,223.252.192.0/19,🔊 Netease
# IP-CIDR,101.71.154.241/32,🔊 Netease
```

PS：网易云音乐，专辑 Dreaming (白日梦)，艺术家：Daydream 匹配到好多奇怪的同名歌，希望匹配歌曲可以同时满足 曲名和艺术家。
