### ISSUE TITLE
mac docker运行后能显示并播放歌曲，但是原本属于灰色的歌却不能播放

### ISSUE THREAD

**Issue by zqcccc** [nondanee/UnblockNeteaseMusic#588]
mac网易云音乐版本是最新的2.3.2(834)
拉了最新的仓库代码到了 `~/Code` 文件夹下后按照 #48 成本配置了证书，配置了 proxifier 后，直接用 node 跑后成功运行，播放原本灰色的歌曲也能正常放了
可是按照一样配置的 docker 启动，歌也是能听的，但是原本是灰色的那些歌都不能放了
```yaml
version: '3'

services:
  unblockmusic:
    container_name: unblockmusic
    restart: always
    image: nondanee/unblockneteasemusic:latest
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ~/Code/UnblockNeteaseMusic/server.key:/usr/src/app/server.key
      - ~/Code/UnblockNeteaseMusic/server.crt:/usr/src/app/server.crt
    command: -p 8080:8081
```
这是 `docker-compose.yml` 的配置，不知哪里出现了问题
话说，win10 上一分钟就可以搞定了美美地用起来，而 mac 真的麻烦
